language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
- pip install coveralls

script: make travis

after_success:
  - coveralls
