language: python
sudo: False
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- nightly # 3.6

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt

script: make travis

after_success:
- coveralls

#notifications:
#  irc:
#    channels: "chat.freenode.net#not-your-server.de"
#    template:
#    - "%{repository} - %{branch} - %{author}: %{commit_subject} - %{message} - Build details : %{build_url}"
#    use_notice: true
